# IMAGES
# openjdk:17-buster    https://github.com/docker-library/openjdk/blob/master/17/jdk/buster/Dockerfile

test-and-publish-update:
    # bgerp/base doesn't work here, something about missing 'libfreetype.so.6'
    image: openjdk:17-buster
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
    before_script:
        - export TZ="CET" && date
        - export GRADLE_USER_HOME=`pwd`/.gradle
    script:
        - apt-get update && apt-get install -y openssh-client rsync git-lfs
        - git checkout -B $CI_COMMIT_REF_NAME
        - git rev-parse --abbrev-ref HEAD
        - sh gradlew checkChanges test doc
        - mkdir ~/.ssh && echo "$KEY_DOC" > ~/.ssh/id_rsa && chmod -R 600 ~/.ssh
        - sh gradlew updateProperties buildUpdate updateLibProperties buildUpdateLib publishUpdate
    rules:
        - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "p11862-documentation"'
          when: never
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: always

test-and-publish-update-master:
    # bgerp/base doesn't work here, something about missing 'libfreetype.so.6'
    image: openjdk:17-buster
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
    before_script:
        - export TZ="CET" && date
        - export GRADLE_USER_HOME=`pwd`/.gradle
    script:
        - apt-get update && apt-get install -y openssh-client rsync git-lfs
        - git checkout -B p00000-master
        - git rev-parse --abbrev-ref HEAD
        - sh gradlew test doc #sonarqube
        - mkdir ~/.ssh && echo "$KEY_DOC" > ~/.ssh/id_rsa && chmod -R 600 ~/.ssh
        - sh gradlew updateProperties buildUpdate updateLibProperties buildUpdateLib
        - sh gradlew changesFile && mv build/changes.txt build/changes.00000.txt
        - sh gradlew publishUpdate
    rules:
        - if: $CI_COMMIT_REF_NAME == "master"
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never

test-integration:
    image: bgerp/base
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
    before_script:
        - export TZ="CET" && date
        - export GRADLE_USER_HOME=`pwd`/.gradle
    script:
        # start MySQL, create DB and user, move bgerp.properties to the current directory
        - /usr/local/bin/docker-bgerp-base.sh
        # for checking custom out
        - apt-get update && apt-get install -y git
        # integration tests are running by with 'bgerp.properties' configuration
        - mkdir -p filestorage && sh gradlew itest -Pskip.custom=false

        ## Activate later with E-to-E tests and markhobson/maven-chrome image: - GRADLE_OPTS=-Xmx1048m sh gradlew --debug -Pdb.host=$DB_ITEST_HOST -Pdb.user=$DB_ITEST_USER -Pdb.pswd="$DB_ITEST_PASSWORD" -Pwebdriver.chrome.driver=/usr/bin/chromedriver integrationTest
        #- sh gradlew -Pdb.host=$DB_ITEST_HOST -Pdb.user=$DB_ITEST_USER -Pdb.pswd="$DB_ITEST_PASSWORD" itest
    # artifacts:
    #     when: always
    #     paths:
    #         - target/reports
    rules:
        - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "p11862-documentation"'
          when: never
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - when: always

test-integration-master:
    image: bgerp/base
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
    before_script:
        - export TZ="CET" && date
        - export GRADLE_USER_HOME=`pwd`/.gradle
    script:
        # start MySQL, create DB and user, move bgerp.properties to the current directory
        - /usr/local/bin/docker-bgerp-base.sh
        # integration tests are running by with 'bgerp.properties' configuration
        - mkdir -p filestorage && sh gradlew itest

        # copy DB and filestorage content to demo server

        # java layer removes those with 'apt-get purge'
        - apt-get update && apt-get install -y openssh-client zip
        # the password is same with MYSQL_ROOT_PASSWORD
        - PWD=`grep db.pswd bgerp.properties | cut -d'=' -f2`
        - mysqldump -uroot -p$PWD --add-drop-table bgerp > build/bgerp.sql
        - cd filestorage && zip -r ../build/filestorage.zip * && cd ..
        # GitLab CI variable
        - echo "$KEY_DEMO" > ./demo.id_rsa && chmod 600 ./demo.id_rsa
        - scp -i ./demo.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build/bgerp.sql demo@bgerp.org:/home/demo
        - scp -i ./demo.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build/filestorage.zip demo@bgerp.org:/home/demo
    rules:
        - if: $CI_COMMIT_REF_NAME == "master"
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: always

publish-doc:
    # bgerp/base doesn't work here, something about missing 'libfreetype.so.6'
    image: openjdk:17-buster
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
    before_script:
        - export TZ="CET" && date
        - export GRADLE_USER_HOME=`pwd`/.gradle
    script:
        - sh gradlew jdoc doc
        - apt-get update && apt-get install -y rsync openssh-client
        - echo "$KEY_DOC" > ./doc.id_rsa && chmod 600 ./doc.id_rsa
        - rsync --delete -Pav -e "ssh -i ./doc.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" target/javadoc/ www@bgerp.org:/home/www/www.bgerp.org/doc/3.0/javadoc/
        - rsync --delete -Pav -e "ssh -i ./doc.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" target/doc/ www@bgerp.org:/home/www/www.bgerp.org/doc/3.0/manual/
    rules:
        - if: $CI_COMMIT_REF_NAME == "p11862-documentation"

publish-source:
    # think about switching to 'bgerp/base' for unification
    image: alpine
    before_script:
        - export TZ="CET" && date
        - export REPO_PUB=/tmp/bgerp-pub
        - apk --no-cache add git git-lfs openssh-client bash
        - mkdir ~/.ssh && echo "$KEY_WWW" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        # only to make git working
        - git config --global user.email "bgerp@bgerp.org"
        - git config --global user.name "BGERP"
    script:
        - REPO_FULL=`pwd`
        - git clone --depth 1 "file://$REPO_FULL" $REPO_PUB
        - COMMIT_COMMENT=`git show -s --format=%s`
        - echo "Set commit author" && chmod +x .gitlab-ci-publish-author.sh && COMMIT_AUTHOR=`bash .gitlab-ci-publish-author.sh`
        - cd $REPO_PUB && rm -r .git && rm .gitlab-ci-publish* && rm .github-fix* && rm -r src.bak
        - git init && git lfs install && git add . && git commit -m "Init"
        - git remote add origin git@github.com:Pingvin235/bgerp.git
        - git fetch && git reset --mixed origin/master
        - git add . && git commit --allow-empty --author="$env:$COMMIT_AUTHOR" -m "$COMMIT_COMMENT"
        - git show --summary
        - git push origin master
    rules:
        - if: $CI_COMMIT_REF_NAME == "master"
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
