# IMAGES
# openjdk:17-buster    https://github.com/docker-library/openjdk/blob/master/17/jdk/buster/Dockerfile

test-and-publish-update:
    # replace to 'bgerp/base' after removing 'ant' dependency
    image: openjdk:17-buster
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
    script:
        - apt-get update && apt-get install -y openssh-client ant rsync git-lfs
        - git checkout -B $CI_COMMIT_REF_NAME
        - git rev-parse --abbrev-ref HEAD
        - sh gradlew checkChanges test buildDoc
        - mkdir ~/.ssh && echo "$KEY_DOC" > ~/.ssh/id_rsa && chmod -R 600 ~/.ssh
        - sh gradlew buildUpdate buildUpdateLib publishUpdate
    except:
        refs:
            - master
            - p11862-documentation

test-and-publish-update-master:
    # replace to 'bgerp/base' after removing 'ant' dependency
    image: openjdk:17-buster
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
    script:
        - apt-get update && apt-get install -y openssh-client ant rsync git-lfs
        - git checkout -B p00000-master
        - git rev-parse --abbrev-ref HEAD
        - sh gradlew test buildDoc #sonarqube
        - mkdir ~/.ssh && echo "$KEY_DOC" > ~/.ssh/id_rsa && chmod -R 600 ~/.ssh
        - sh gradlew buildUpdate buildUpdateLib
        - sh gradlew patchChanges && mv build/changes.txt build/changes.00000.txt
        - sh gradlew publishUpdate
    only:
        refs:
            - master

test-integration:
    image: bgerp/base
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
    script:
        # start MySQL, create DB and user, move bgerp.properties to the current directory
        - /usr/local/bin/docker-bgerp-base.sh
        # integration tests are running by with 'bgerp.properties' configuration
        - mkdir -p filestorage && sh gradlew itest

        ## Activate later with E-to-E tests and markhobson/maven-chrome image: - GRADLE_OPTS=-Xmx1048m sh gradlew --debug -Pdb.host=$DB_ITEST_HOST -Pdb.user=$DB_ITEST_USER -Pdb.pswd="$DB_ITEST_PASSWORD" -Pwebdriver.chrome.driver=/usr/bin/chromedriver integrationTest
        #- sh gradlew -Pdb.host=$DB_ITEST_HOST -Pdb.user=$DB_ITEST_USER -Pdb.pswd="$DB_ITEST_PASSWORD" itest
    except:
        refs:
            - master
            - p11862-documentation

test-integration-master:
    image: bgerp/base
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
    script:
        # start MySQL, create DB and user, move bgerp.properties to the current directory
        - /usr/local/bin/docker-bgerp-base.sh
        # integration tests are running by with 'bgerp.properties' configuration
        - mkdir -p filestorage && sh gradlew itest

        # copy DB and filestorage content to demo server

        # java layer removes those with 'apt-get purge'
        - apt-get update && apt-get install -y openssh-client zip
        # the password is same with MYSQL_ROOT_PASSWORD
        - PWD=`grep db.pswd bgerp.properties | cut -d'=' -f2`
        - mysqldump -uroot -p$PWD --add-drop-table bgerp > build/bgerp.sql
        - zip -r -j build/filestorage.zip filestorage
        # GitLab CI variable
        - echo "$KEY_DEMO" > ./demo.id_rsa && chmod 600 ./demo.id_rsa
        - scp -i ./demo.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build/bgerp.sql demo@bgerp.org:/home/demo
        - scp -i ./demo.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build/filestorage.zip demo@bgerp.org:/home/demo
    only:
        refs:
            - master

publish-doc:
    # bgerp/base doesn't work here, something about missing 'libfreetype.so.6'
    image: openjdk:17-buster
    cache:
        paths:
            - .gradle/wrapper
            - .gradle/caches
    script:
        - sh gradlew buildJavaDoc buildDoc
        - apt-get update && apt-get install -y rsync openssh-client
        - echo "$KEY_DOC" > ./doc.id_rsa && chmod 600 ./doc.id_rsa
        - rsync --delete -Pav -e "ssh -i ./doc.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" target/javadoc/ www@bgerp.org:/home/www/www.bgerp.org/doc/3.0/javadoc/
        - rsync --delete -Pav -e "ssh -i ./doc.id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" target/doc/ www@bgerp.org:/home/www/www.bgerp.org/doc/3.0/manual/
    only:
        refs:
            - p11862-documentation

publish-source:
    # think about switching to 'bgerp/base' for unification
    image: alpine
    before_script:
        - export REPO_PUB=/tmp/bgerp-pub
        - apk --no-cache add git git-lfs openssh-client bash
        - mkdir ~/.ssh && echo "$KEY_WWW" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        # only to make git working
        - git config --global user.email "bgerp@bgerp.org"
        - git config --global user.name "BGERP"
    script:
        - REPO_FULL=`pwd`
        - git clone --depth 1 "file://$REPO_FULL" $REPO_PUB
        - COMMIT_COMMENT=`git show -s --format=%s`
        - echo "Set commit author" && chmod +x .gitlab-ci-publish-author.sh && COMMIT_AUTHOR=`bash .gitlab-ci-publish-author.sh`
        - cd $REPO_PUB && rm -r .git && rm .gitlab-ci-publish* && rm .github-fix* && rm -r src.bak
        - git init && git lfs install && git add . && git commit -m "Init"
        - git remote add origin git@github.com:Pingvin235/bgerp.git
        - git fetch && git reset --mixed origin/master
        - git add . && git commit --allow-empty --author="$env:$COMMIT_AUTHOR" -m "$COMMIT_COMMENT"
        - git show --summary
        - git push origin master
    only:
        refs:
            - master

