= Welcome to BGERP!
:toc:

== About
The BGERP software is an fast and flexible CRM / ERP / Project Management system, 
initially developed for Telecommunication Operators in ~ 2011 year.
From beginning we were extremely focused on performance and configurability and after 
years of work and experiments got a quite popular branch solution in Russia.

In parallel, we had to solve the problem of organizing Software Development and Support.
And found, that our own program of Process Management fits for this perfect as well.

Our biggest customers run databases with tens millions of processes and millions of customers,
all the solutions have validated by time. The product also is initially adopted for large enterprises 
and contains feature-reach permission and user structuring model. 

In same time BGERP is very easy to install and maintain, it has only Java and MySQL Server as dependencies
and may be running in few minutes at any Linux PC. Without any Cloud Service lock all the data 
are completely controlled by owner.

Current functionality:
[square]
* Generic Business Process Management, Planning and Support process for Software Development, Telecommunication and other branches;
* E-Mail tracking same as multi-channel messaging using: Slack, Telegram, PhpBB Forum, Asterisk PBX, Android App;
* Parameterized customers, users, organization structure, process types, permissions;
* Many extension points: JEXL / JSP / Java for customization, REST API / DB structure description - for external integration, and modular architecture for writing new plugins;
* One-click update using Web interface with backup.

Our next goals:
[square]
* Personal and family planning tool inspired by link:https://en.wikipedia.org/wiki/Getting_Things_Done[GTD] principles;
* The new way of work with E-Mail, integrated with project management;
* Calendars and Contacts from Google or other source;
* GitHub, GitLab and other development platforms.

Actually there are very many of them, you may see actual link:http://crm.bitel.ru/open/blow/bgerp[Development Planning Blow Board].

CAUTION: The translation is in progress, <<contact, contact us>> to let know, what is needed first.

[[get]]
== Get it
Since 2015 we have successfully switched to Continuous Delivery development model.
This means, that releases are published periodically from master branch after appropriate testing and accepting 
in branches. 

On the link:https://bgerp.org/doc/3.0/manual/project.html[Project description page] you may find 
all required for developers information. Installation instructions for normal humans and Demo system are coming soon.

To be aware about new releases you may follow *PUBLISH* messages in master branch 
or subscribe to link:https://bgerp.ru/changes.xml[RSS] feed.

Text based link:https://bgerp.ru/changes.txt[ChangeLog].

CAUTION: The translation is in progress, <<contact, contact us>> to let know, what is needed first.

[[contact]]
== Contact us
Our primary communication tool is the link:https://t.me/bgerp[Telegram Group] or write E-Mail to mailto:bgerpp@gmail.com[bgerpp@gmail.com]
Although most of the communication there is now in Russian, we can also support the conversation in bad English or awful German.
We may even find native Tatar and Bashkir speakers for you, so do not hesitate to join.
