CREATE TABLE IF NOT EXISTS `invoice` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `type_id` INT NOT NULL,
  `date_from` DATE NOT NULL,
  `date_to` DATE,
  `process_id` INT NOT NULL,
  `number_cnt` INT NOT NULL,
  `number` CHAR(20) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `created_dt` DATETIME NOT NULL,
  `created_user_id` INT NOT NULL,
  `sent_dt` DATETIME,
  `sent_user_id` INT,
  `payment_date` DATE,
  `payment_user_id` INT,
  `positions` TEXT NOT NULL,
  KEY process_id(`process_id`),
  KEY date_from(`date_from`),
  UNIQUE KEY `number`(`number`)
);
