
package ru.bgcrm.plugin.bgbilling.ws.helpdesk;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BGMessageException", targetNamespace = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/")
public class BGMessageException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BGMessageException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BGMessageException_Exception(String message, BGMessageException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BGMessageException_Exception(String message, BGMessageException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.bgcrm.plugin.bgbilling.ws.helpdesk.BGMessageException
     */
    public BGMessageException getFaultInfo() {
        return faultInfo;
    }

}
