
package ru.bgcrm.plugin.bgbilling.ws.helpdesk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelpdeskService", targetNamespace = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/", wsdlLocation = "http://billing.office.bitel.ru:8081/executer/ru.bitel.bgbilling.plugins.helpdesk/HelpdeskService?wsdl")
public class HelpdeskService_Service
    extends Service
{

    private final static URL HELPDESKSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELPDESKSERVICE_EXCEPTION;
    private final static QName HELPDESKSERVICE_QNAME = new QName("http://service.common.helpdesk.plugins.bgbilling.bitel.ru/", "HelpdeskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://billing.office.bitel.ru:8081/executer/ru.bitel.bgbilling.plugins.helpdesk/HelpdeskService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELPDESKSERVICE_WSDL_LOCATION = url;
        HELPDESKSERVICE_EXCEPTION = e;
    }

    public HelpdeskService_Service() {
        super(__getWsdlLocation(), HELPDESKSERVICE_QNAME);
    }

    public HelpdeskService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELPDESKSERVICE_QNAME, features);
    }

    public HelpdeskService_Service(URL wsdlLocation) {
        super(wsdlLocation, HELPDESKSERVICE_QNAME);
    }

    public HelpdeskService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELPDESKSERVICE_QNAME, features);
    }

    public HelpdeskService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelpdeskService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelpdeskService
     */
    @WebEndpoint(name = "HelpdeskService")
    public HelpdeskService getHelpdeskService() {
        return super.getPort(new QName("http://service.common.helpdesk.plugins.bgbilling.bitel.ru/", "HelpdeskService"), HelpdeskService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelpdeskService
     */
    @WebEndpoint(name = "HelpdeskService")
    public HelpdeskService getHelpdeskService(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.common.helpdesk.plugins.bgbilling.bitel.ru/", "HelpdeskService"), HelpdeskService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELPDESKSERVICE_EXCEPTION!= null) {
            throw HELPDESKSERVICE_EXCEPTION;
        }
        return HELPDESKSERVICE_WSDL_LOCATION;
    }

}
