= Плагин Telegram
:toc:

== О плагине
Плагин предназначен для интеграции BGERP с месседжером link:https://telegram.org/[Telegram] и предоставляет функционал:
[square]
* привязка процесса к чату группы или чату пользователя Telegram;
* привязка пользователя к чату группы или чату пользователя Telegram;

== Настройка 
[arabic]
. В BotFather  создать своего бота, прописать его название и токен в конфигурации. 
. Создать параметры для пользователя и процесса, где будут храниться id чатов и прописать их в конфигурации .

После запуска найти в телеграмм своего бота. 
Eсли разговор один на один :
	- команды */getid* - получить id и вписать в параметр своего пользователя, можно вписать и в параметр процесса 
	- */start* после чего ввести в чате пользователя и пароль, тогда в параметр пользователя ид чата занесется само

Можно добавить бота в чат, тогда : 
	- */getid* и заносим его в параметр процесса ил пользователя. 

Пример настройки 

[source]
----
telegram:botStart=1

# настройки прокси, для России желательны  
telegram:proxyHost=111.223.75.181  
telegram:proxyPort=8888
# SOCKS5 , HTTP
telegram:proxyType=SOCKS5

# в BotFather создать своего бота, прописать его название и токен
telegram:token=842416376:AAFGsYLCgqG6eKcsZPy6gLCjge_klgUiWHE
telegram:botName=TestBgErp_bot

# параметр пользователя в котором будет храниться chatId
telegram:userParamId=90

# параметр процесса в котором будет храниться chatId
telegram:processParamId=91
----



== Настройка типа процесса
В конфигурации типа процесса может быть настроена автоматизация работы с Telegram  с помощью скрипта в doExpression <<../../kernel/process/processing.adoc#, простого обработчика событий>>. 
Ниже приведено несколько примеров возможных действий по различным событиям в процессе.

При изменении статуса, отправляеться сообщение в чаты всех исполнителей процесса и чат самого процесса:

[source]
----
onProcessEvent.1.events=statusChanged
onProcessEvent.1.doExpression=<<END
	telegram.sendMessage(process, "Изменился статус");
END
----

При изменении статуса, отправляеться сообщение только в чат самого процесса:
[source]
----
onProcessEvent.2.events=statusChanged
onProcessEvent.2.doExpression=<<END
	telegram.sendMassageForProcess(process, "Изменился статус");
END
----


Объект *telegram* класса javadoc:ru.bgerp.plugin.telegram.DefaultProcessorFunctions[] с функциями API предоставляется плагином.