
package ru.bgcrm.plugin.bgbilling.ws.tariff.option;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TariffOptionService", targetNamespace = "http://service.common.option.tariff.kernel.bgbilling.bitel.ru/", wsdlLocation = "http://billing:8081/executer/ru.bitel.bgbilling.kernel.tariff.option/TariffOptionService?wsdl")
public class TariffOptionService_Service
    extends Service
{

    private final static URL TARIFFOPTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException TARIFFOPTIONSERVICE_EXCEPTION;
    private final static QName TARIFFOPTIONSERVICE_QNAME = new QName("http://service.common.option.tariff.kernel.bgbilling.bitel.ru/", "TariffOptionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://billing:8081/executer/ru.bitel.bgbilling.kernel.tariff.option/TariffOptionService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TARIFFOPTIONSERVICE_WSDL_LOCATION = url;
        TARIFFOPTIONSERVICE_EXCEPTION = e;
    }

    public TariffOptionService_Service() {
        super(__getWsdlLocation(), TARIFFOPTIONSERVICE_QNAME);
    }

    public TariffOptionService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TARIFFOPTIONSERVICE_QNAME, features);
    }

    public TariffOptionService_Service(URL wsdlLocation) {
        super(wsdlLocation, TARIFFOPTIONSERVICE_QNAME);
    }

    public TariffOptionService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TARIFFOPTIONSERVICE_QNAME, features);
    }

    public TariffOptionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TariffOptionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TariffOptionService
     */
    @WebEndpoint(name = "TariffOptionService")
    public TariffOptionService getTariffOptionService() {
        return super.getPort(new QName("http://service.common.option.tariff.kernel.bgbilling.bitel.ru/", "TariffOptionService"), TariffOptionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TariffOptionService
     */
    @WebEndpoint(name = "TariffOptionService")
    public TariffOptionService getTariffOptionService(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.common.option.tariff.kernel.bgbilling.bitel.ru/", "TariffOptionService"), TariffOptionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TARIFFOPTIONSERVICE_EXCEPTION!= null) {
            throw TARIFFOPTIONSERVICE_EXCEPTION;
        }
        return TARIFFOPTIONSERVICE_WSDL_LOCATION;
    }

}
