<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %><%--
--%><%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %><%--
--%><%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %><%--
--%><%@ taglib uri="http://java.sun.com/jsp/jstl/xml" prefix="x" %><%--
--%><%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql" %><%--
--%><%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean" %><%--
--%><%@ taglib uri="http://struts.apache.org/tags-html" prefix="html" %><%--
--%><%@ taglib uri="http://struts.apache.org/tags-logic" prefix="logic" %><%--
--%><%@ taglib uri="http://struts.apache.org/tags-tiles" prefix="tiles" %><%--
--%><%@ taglib uri="http://bgrcrm.ru/jsp/taglib/util" prefix="u"%><%--
--%><%@ taglib uri="http://bgrcrm.ru/jsp/taglib/permission" prefix="p"%><%--
--%><%@ taglib prefix="ui" tagdir="/WEB-INF/tags/ui"%><%--
--%><%@ taglib prefix="shell" tagdir="/WEB-INF/tags/shell"%>
