= Install
:toc:

[[system-requirements]]
== System requirements
Minimal system requirements for running server with BGERP + MySQL:
[square]
* OS Linux, preferably RPM based: CentOS or RHEL, because the samples below;
* CPU core equal Intel x86 500 MHz, recommended - 1 GHz;
* 512 MB RAM, recommended - 1 GB.

[[mysql]]
== MySQL
*Original* MySQL DB Server version *8.0* or newer. 

Different forks of MySQL (Maria, Percona) does not fit because of missing <<../plugin/fulltext/index.adoc#, fulltext>> index support.
Here is the test query to verify it:
[snippet, from="CREATE", to=");"]
link:../../../build/update/patch_fulltext.sql#L1-L9[build/update/patch_fulltext.sql]

Install instructions:
[square]
* link:https://www.mysqltutorial.org/install-mysql-centos[MySQL 8 on CentOS]
* link:https://hub.docker.com/_/mysql[MySQL using Docker] - in case of already installed MySQL with different version on your server.

Check the required options below in *[mysqld]* section in file *my.cnf*:
----
[mysqld]
sql-mode=
----
IMPORTANT: *sql-mode* must be set exactly to empty string, as shown in the example. If sql-mode is not defined - add it, if missing - make value  DB creation script contains correctness of it any case.

You will also need a root access to the MySQL Server one time.

[[java]]
== Java
Required version *OpenJDK 11*, may be installed so:
[square, sh]
----
sudo yum update
sudo yum install -y java-11-openjdk-devel
----

IMPORTANT: Check, what commands *java* and *javac* are available after installation.

[[install-linux]]
== The application
All the operations require *root* user.

Check and install if needed script dependencies:
[source, sh]
----
sudo yum update
sudo yum install -y zip pwgen wget mysql-community-client
----

Download archive and unpack it:
[source, sh]
----
wget https://bgerp.org/download/3.0/bgerp.zip -O /tmp/bgerp.zip &&
unzip /tmp/bgerp.zip -d /opt &&
chmod 744 /opt/BGERP/*.sh
----

Generate DB password ant put it in files:
[source, sh]
----
ERP_DB_PWD=`pwgen` && export EPR_DB_PWD &&
echo "Setting DB password: '$ERP_DB_PWD'" &&
sed -i "s/GENERATED_PASSWORD/$ERP_DB_PWD/" /opt/BGERP/bgerp.properties &&
sed -i "s/GENERATED_PASSWORD/'$ERP_DB_PWD'/" /opt/BGERP/db.sql
----

Run DB user and structure creation:
[source, sh]
----
mysql --default-character-set=utf8 -h127.0.0.1 -uroot -p < /opt/BGERP/db.sql
----

// TODO: Take filestorage from Demo.
Apply data from the Demo-system:
[source, sh]
----
wget https://demo.bgerp.org/bgerp.sql -O /opt/BGERP/bgerp.sql
mysql --default-character-set=utf8 -h127.0.0.1 -uroot -p < /opt/BGERP/bgerp.sql
----

Change if needed in *bgerp.properties* DB server host, HTTP and management ports, in *setenv.sh* *JAVA_HOME*:
[source, sh]
----
JAVA_HOME=/usr
if [ -z "$JAVA_HOME" ]; then
  echo "The JAVA_HOME environment variable is not defined"
  echo "This environment variable is needed to run this program"
  exit 1
fi
----
*java* and *javac* are looked in *$JAVA_HOME/bin/*

For starting/stopping use *erp_start.sh/erp_stop.sh*. *erp_status.sh* - shows current status of the application.
After starting check *log/bgerp.log* and *log/bgerp.out* on errors.

[[systemd]]
=== Systemd
Скрипт сервиса Systemd расположен в *scripts/bgerp.service*, переместите его в каталог */etc/systemd/system/*. 
Затем выполните команды:
[source, bash]
----
systemctl daemon-reload
systemctl enable bgerp
----
Для автозапуска приложения при загрузке системы.

[[update]]
== Обновление
IMPORTANT: Изучите link:https://bgerp.ru#download[лог обновлений], там могут содержаться важные сведения либо инструкции. 

[[installer-iface]]
=== Интерфейс
В оснастке *Пуск - Администрирование - Приложение - Статус приложения* доступен просмотр текущей версии приложения,
списка с логами обновлений. Для всех операций неявно используются <<installer, консольные утилиты>>, описанные далее.

Раздел *Обновление* - обновление на текущую версию системы и набора библиотек.
Выполняемая <<installer, команда>>:
[source, bash]
----
./backup.sh && ./installer.sh update(f) && ./erp_restart.sh
----

Раздел *Обновление на изменение* - загрузка пакетов обновления <<../project.adoc#build-update, изменения>> по коду процесса.
Выполняемая <<installer, команда>>:
----
./backup.sh && ./installer.sh install update_3.0_xxxx.zip && ./erp_restart.sh
----

NOTE: Повторное *Обновление* после *Обновления на изменение* позволит сбросить сервер в состояние последнего официального апдейта.

[[installer]]
=== Консольные утилиты
[CAUTION]
====
Перед установкой обновления всегда делайте резервную копию программы при помощи скрипта *backup.sh* 
[square]
* При указании параметра *db* скрипт создаст резервную копию БД, данные для подключения к серверу MySQL берутся из файла *bgerp.properties*
* Резервные копии сохраняются в папке *backup* в файлах с форматом имени *год-месяц-дата-время(.db).zip*, наличие подстроки *db* означает, что в архиве есть дамп БД
====

Для обновления вызовите команду:
[source, bash]
----
./installer.sh update
----

Для обновления системы на иную версию (не 3.0) вызовите команду:
[source, bash]
----
./installer.sh update <version>
----

например:
[source, bash]
----
./installer.sh update 3.0
----

Запуск скрипта без параметров выводит подсказку по дополнительным командам:
[square]
* *updatef* - принудительное обновлении на последнюю версию без сравнения её с установленной;
* *update <version>* - установка другой версии BGERP, версия соответствует окончанию адреса FTP;
* *killhash* - очистка хэшей применённых SQL обновлений с последующим выполнением всех команд, рекомендуется попробовать при наличии ошибок SQL запросов в обновлении;
* *install <zip>* - установка обновления из ZIP архива.

Рекомендованный однострочик для обновления (можете исключить db параметр для ускорения и выполнять бакап базы только эпизодически):
[source, bash]
----
./backup.sh db && ./installer.sh update && ./erp_restart.sh
----

[[stored-procedures]]
=== Хранимые процедуры обновления
Для изменений структуры БД в скриптах внутри пакетов обновлении используются хранимые процедуры. Например:
[source]
----
CALL add_column_if_not_exists('task', 'config', 'TEXT NOT NULL');
----

При восстановлении БД из резервной копии они пропадают. Процедура обновления происходит с ошибками. 
В этом случае необходимо выполнить следующие команды:
[source, bash]
----
./installer.sh killhash
./installer.sh updatef
----

Первая удаляет из БД информацию о уже применённых обновлениях структуры, вторая - производит повторное выполнение всех скриптов.

== Плагины
Плагины дополняют функционал ядра, позволяя максимально гибко сконфигурировать систему под нужды конкретной организации-пользователя. В данный момент все доступные плагины включены в общую сборку. Для отключения функций плагина необходимо удалить XML файл описания из каталога *BGERP/plugin*.

[[nginx]]
== NGINX
При классической схеме сервер BGERP располагается во внутренней сети организации, NGINX позволяет организовать доступ извне к открытому <<interface.adoc#, интерфейсу>> сервера.

Документация по NGINX доступна здесь: http://sysoev.ru/nginx/docs/

=== Пример
BGERP запущен на внутреннем адресе crm.inner.bitel.ru. Снаружи на хосте crm.bitel.ru доступен только открытый интерфейс http://crm.bitel.ru/open
----
server {
    listen          80;
    server_name     crm.bitel.ru;

    access_log      /var/log/nginx/crm.bitel.ru.access.log;
    client_max_body_size    50m;

    # для открытия обычного интерфейса - добавить login.do|user
    location ~ ^/(open|img|images|css|lib|js)(.*)$ {
        resolver                X.X.X.X;.
        if ($args = '') {
            proxy_pass  http://crm.inner.bitel.ru/$1$2;
        }
        if ($args != '') {
            proxy_pass  http://crm.inner.bitel.ru/$1$2?$args;
        }
        proxy_redirect          http://crm.inner.bitel.ru/ http://crm.bitel.ru/;
        proxy_set_header        Connection close;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_read_timeout      300;
        gzip_proxied            expired no-cache no-store private no_last_modified no_etag auth;
    }
}
----


