
package ru.bgcrm.plugin.bgbilling.ws.helpdesk.param;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelpdeskParamService", targetNamespace = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelpdeskParamService {


    /**
     * 
     * @param contractId
     * @return
     *     returns ru.bgcrm.plugin.bgbilling.ws.helpdesk.Properties
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProperties", targetNamespace = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.helpdesk.param.GetProperties")
    @ResponseWrapper(localName = "getPropertiesResponse", targetNamespace = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.helpdesk.param.GetPropertiesResponse")
    @Action(input = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/HelpdeskParamService/getPropertiesRequest", output = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/HelpdeskParamService/getPropertiesResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/HelpdeskParamService/getProperties/Fault/BGException")
    })
    public Properties getProperties(
        @WebParam(name = "contractId", targetNamespace = "")
        int contractId)
        throws BGException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<ru.bgcrm.plugin.bgbilling.ws.helpdesk.DirectoryItem>
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getModeList", targetNamespace = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.helpdesk.param.GetModeList")
    @ResponseWrapper(localName = "getModeListResponse", targetNamespace = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.helpdesk.param.GetModeListResponse")
    @Action(input = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/HelpdeskParamService/getModeListRequest", output = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/HelpdeskParamService/getModeListResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/HelpdeskParamService/getModeList/Fault/BGException")
    })
    public List<DirectoryItem> getModeList()
        throws BGException_Exception
    ;

    /**
     * 
     * @param contractId
     * @return
     *     returns java.lang.String
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContractCurrentMode", targetNamespace = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.helpdesk.param.GetContractCurrentMode")
    @ResponseWrapper(localName = "getContractCurrentModeResponse", targetNamespace = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.helpdesk.param.GetContractCurrentModeResponse")
    @Action(input = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/HelpdeskParamService/getContractCurrentModeRequest", output = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/HelpdeskParamService/getContractCurrentModeResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://service.common.helpdesk.plugins.bgbilling.bitel.ru/HelpdeskParamService/getContractCurrentMode/Fault/BGException")
    })
    public String getContractCurrentMode(
        @WebParam(name = "contractId", targetNamespace = "")
        int contractId)
        throws BGException_Exception
    ;

}
