
package ru.bgcrm.plugin.bgbilling.ws.contract.balance.paymcharge;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentAndChargeService", targetNamespace = "http://common.balance.contract.kernel.bgbilling.bitel.ru/", wsdlLocation = "http://billing:8081/executer/ru.bitel.bgbilling.kernel.contract.balance/PaymentAndChargeService?wsdl")
public class PaymentAndChargeService_Service
    extends Service
{

    private final static URL PAYMENTANDCHARGESERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTANDCHARGESERVICE_EXCEPTION;
    private final static QName PAYMENTANDCHARGESERVICE_QNAME = new QName("http://common.balance.contract.kernel.bgbilling.bitel.ru/", "PaymentAndChargeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://billing:8081/executer/ru.bitel.bgbilling.kernel.contract.balance/PaymentAndChargeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTANDCHARGESERVICE_WSDL_LOCATION = url;
        PAYMENTANDCHARGESERVICE_EXCEPTION = e;
    }

    public PaymentAndChargeService_Service() {
        super(__getWsdlLocation(), PAYMENTANDCHARGESERVICE_QNAME);
    }

    public PaymentAndChargeService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTANDCHARGESERVICE_QNAME, features);
    }

    public PaymentAndChargeService_Service(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTANDCHARGESERVICE_QNAME);
    }

    public PaymentAndChargeService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTANDCHARGESERVICE_QNAME, features);
    }

    public PaymentAndChargeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentAndChargeService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentAndChargeService
     */
    @WebEndpoint(name = "PaymentAndChargeService")
    public PaymentAndChargeService getPaymentAndChargeService() {
        return super.getPort(new QName("http://common.balance.contract.kernel.bgbilling.bitel.ru/", "PaymentAndChargeService"), PaymentAndChargeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentAndChargeService
     */
    @WebEndpoint(name = "PaymentAndChargeService")
    public PaymentAndChargeService getPaymentAndChargeService(WebServiceFeature... features) {
        return super.getPort(new QName("http://common.balance.contract.kernel.bgbilling.bitel.ru/", "PaymentAndChargeService"), PaymentAndChargeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTANDCHARGESERVICE_EXCEPTION!= null) {
            throw PAYMENTANDCHARGESERVICE_EXCEPTION;
        }
        return PAYMENTANDCHARGESERVICE_WSDL_LOCATION;
    }

}
