
package ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BGException", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/")
public class BGException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BGException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BGException_Exception(String message, BGException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BGException_Exception(String message, BGException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.BGException
     */
    public BGException getFaultInfo() {
        return faultInfo;
    }

}
