
package ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import java.util.Date;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSUserCardCopy", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSUserCardCopy {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.UserCardCopy>
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserCardCopyList", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.GetUserCardCopyList")
    @ResponseWrapper(localName = "getUserCardCopyListResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.GetUserCardCopyListResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/getUserCardCopyListRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/getUserCardCopyListResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/getUserCardCopyList/Fault/BGException")
    })
    public List<UserCardCopy> getUserCardCopyList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.UserCardCopy>
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserCardCopyListByDate", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.GetUserCardCopyListByDate")
    @ResponseWrapper(localName = "getUserCardCopyListByDateResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.GetUserCardCopyListByDateResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/getUserCardCopyListByDateRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/getUserCardCopyListByDateResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/getUserCardCopyListByDate/Fault/BGException")
    })
    public List<UserCardCopy> getUserCardCopyListByDate(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Date arg1)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws BGException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserCardCopy", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.UpdateUserCardCopy")
    @ResponseWrapper(localName = "updateUserCardCopyResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.UpdateUserCardCopyResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/updateUserCardCopyRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/updateUserCardCopyResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/updateUserCardCopy/Fault/BGException")
    })
    public void updateUserCardCopy(
        @WebParam(name = "arg0", targetNamespace = "")
        UserCardCopy arg0)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws BGException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserCardCopy", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.DeleteUserCardCopy")
    @ResponseWrapper(localName = "deleteUserCardCopyResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.DeleteUserCardCopyResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/deleteUserCardCopyRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/deleteUserCardCopyResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/deleteUserCardCopy/Fault/BGException")
    })
    public void deleteUserCardCopy(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.LogEntry>
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logList", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.LogList")
    @ResponseWrapper(localName = "logListResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy.LogListResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/logListRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/logListResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCardCopy/logList/Fault/BGException")
    })
    public List<LogEntry> logList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Object> arg1)
        throws BGException_Exception
    ;

}
