
package ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.copy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSUserCardCopy", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", wsdlLocation = "http://192.168.169.17:8080/bgbilling/executer/modules.cerbercrypt/4/UserCardCopy?wsdl")
public class WSUserCardCopy_Service
    extends Service
{

    private final static URL WSUSERCARDCOPY_WSDL_LOCATION;
    private final static WebServiceException WSUSERCARDCOPY_EXCEPTION;
    private final static QName WSUSERCARDCOPY_QNAME = new QName("http://common.cerbercrypt.modules.bgbilling.bitel.ru/", "WSUserCardCopy");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.169.17:8080/bgbilling/executer/modules.cerbercrypt/4/UserCardCopy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSUSERCARDCOPY_WSDL_LOCATION = url;
        WSUSERCARDCOPY_EXCEPTION = e;
    }

    public WSUserCardCopy_Service() {
        super(__getWsdlLocation(), WSUSERCARDCOPY_QNAME);
    }

    public WSUserCardCopy_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSUSERCARDCOPY_QNAME, features);
    }

    public WSUserCardCopy_Service(URL wsdlLocation) {
        super(wsdlLocation, WSUSERCARDCOPY_QNAME);
    }

    public WSUserCardCopy_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSUSERCARDCOPY_QNAME, features);
    }

    public WSUserCardCopy_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSUserCardCopy_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSUserCardCopy
     */
    @WebEndpoint(name = "WSUserCardCopy")
    public WSUserCardCopy getWSUserCardCopy() {
        return super.getPort(new QName("http://common.cerbercrypt.modules.bgbilling.bitel.ru/", "WSUserCardCopy"), WSUserCardCopy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSUserCardCopy
     */
    @WebEndpoint(name = "WSUserCardCopy")
    public WSUserCardCopy getWSUserCardCopy(WebServiceFeature... features) {
        return super.getPort(new QName("http://common.cerbercrypt.modules.bgbilling.bitel.ru/", "WSUserCardCopy"), WSUserCardCopy.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSUSERCARDCOPY_EXCEPTION!= null) {
            throw WSUSERCARDCOPY_EXCEPTION;
        }
        return WSUSERCARDCOPY_WSDL_LOCATION;
    }

}
