
package ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import java.util.Date;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSUserCard", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
@Deprecated
public interface WSUserCard {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.UserCard>
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserCardList", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetUserCardList")
    @ResponseWrapper(localName = "getUserCardListResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetUserCardListResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getUserCardListRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getUserCardListResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getUserCardList/Fault/BGException")
    })
    public List<UserCard> getUserCardList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws BGException_Exception
     * @throws BGMessageException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserCard", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.UpdateUserCard")
    @ResponseWrapper(localName = "updateUserCardResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.UpdateUserCardResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/updateUserCardRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/updateUserCardResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/updateUserCard/Fault/BGException"),
        @FaultAction(className = BGMessageException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/updateUserCard/Fault/BGMessageException")
    })
    public void updateUserCard(
        @WebParam(name = "arg0", targetNamespace = "")
        UserCard arg0)
        throws BGException_Exception, BGMessageException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.UserCard
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserCard", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetUserCard")
    @ResponseWrapper(localName = "getUserCardResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetUserCardResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getUserCardRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getUserCardResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getUserCard/Fault/BGException")
    })
    public UserCard getUserCard(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws BGException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserCard", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.DeleteUserCard")
    @ResponseWrapper(localName = "deleteUserCardResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.DeleteUserCardResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/deleteUserCardRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/deleteUserCardResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/deleteUserCard/Fault/BGException")
    })
    public void deleteUserCard(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws BGException_Exception
    ;

    /**
     * 
     * @return
     *     returns ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.DataMap
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSystemInfo", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetSystemInfo")
    @ResponseWrapper(localName = "getSystemInfoResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetSystemInfoResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getSystemInfoRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getSystemInfoResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getSystemInfo/Fault/BGException")
    })
    public DataMap getSystemInfo()
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkSubscriptionCost", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.CheckSubscriptionCost")
    @ResponseWrapper(localName = "checkSubscriptionCostResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.CheckSubscriptionCostResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/checkSubscriptionCostRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/checkSubscriptionCostResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/checkSubscriptionCost/Fault/BGException")
    })
    public BigDecimal checkSubscriptionCost(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Date arg2)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.UserCard>
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMultiroomBasecards", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetMultiroomBasecards")
    @ResponseWrapper(localName = "getMultiroomBasecardsResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetMultiroomBasecardsResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getMultiroomBasecardsRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getMultiroomBasecardsResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getMultiroomBasecards/Fault/BGException")
    })
    public List<UserCard> getMultiroomBasecards(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws BGException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "releaseSlave", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.ReleaseSlave")
    @ResponseWrapper(localName = "releaseSlaveResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.ReleaseSlaveResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/releaseSlaveRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/releaseSlaveResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/releaseSlave/Fault/BGException")
    })
    public void releaseSlave(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.IdTitle>
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContractObjects", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetContractObjects")
    @ResponseWrapper(localName = "getContractObjectsResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetContractObjectsResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getContractObjectsRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getContractObjectsResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getContractObjects/Fault/BGException")
    })
    public List<IdTitle> getContractObjects(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.UserCard>
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCardListByObject", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetCardListByObject")
    @ResponseWrapper(localName = "getCardListByObjectResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.GetCardListByObjectResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getCardListByObjectRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getCardListByObjectResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/getCardListByObject/Fault/BGException")
    })
    public List<UserCard> getCardListByObject(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.LogEntry>
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logList", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.LogList")
    @ResponseWrapper(localName = "logListResponse", targetNamespace = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.cerbercrypt.usercard.LogListResponse")
    @Action(input = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/logListRequest", output = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/logListResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://common.cerbercrypt.modules.bgbilling.bitel.ru/WSUserCard/logList/Fault/BGException")
    })
    public List<LogEntry> logList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Object> arg1)
        throws BGException_Exception
    ;

}
