
package ru.bgcrm.plugin.bgbilling.ws.contract.status51;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 * Переделать на JSON-RPC.
 */
@Deprecated
@WebServiceClient(name = "WSContractStatusMonitor", targetNamespace = "http://common.status.contract.kernel.bgbilling.bitel.ru/", wsdlLocation = "http://127.0.0.1:8080/bgbilling/executer/kernel.contract.status/ContractStatusMonitor?wsdl")
public class WSContractStatusMonitor_Service
    extends Service
{

    private final static URL WSCONTRACTSTATUSMONITOR_WSDL_LOCATION;
    private final static WebServiceException WSCONTRACTSTATUSMONITOR_EXCEPTION;
    private final static QName WSCONTRACTSTATUSMONITOR_QNAME = new QName("http://common.status.contract.kernel.bgbilling.bitel.ru/", "WSContractStatusMonitor");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/bgbilling/executer/kernel.contract.status/ContractStatusMonitor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCONTRACTSTATUSMONITOR_WSDL_LOCATION = url;
        WSCONTRACTSTATUSMONITOR_EXCEPTION = e;
    }

    public WSContractStatusMonitor_Service() {
        super(__getWsdlLocation(), WSCONTRACTSTATUSMONITOR_QNAME);
    }

    public WSContractStatusMonitor_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCONTRACTSTATUSMONITOR_QNAME, features);
    }

    public WSContractStatusMonitor_Service(URL wsdlLocation) {
        super(wsdlLocation, WSCONTRACTSTATUSMONITOR_QNAME);
    }

    public WSContractStatusMonitor_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCONTRACTSTATUSMONITOR_QNAME, features);
    }

    public WSContractStatusMonitor_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSContractStatusMonitor_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSContractStatusMonitor
     */
    @WebEndpoint(name = "WSContractStatusMonitor")
    public WSContractStatusMonitor getWSContractStatusMonitor() {
        return super.getPort(new QName("http://common.status.contract.kernel.bgbilling.bitel.ru/", "WSContractStatusMonitor"), WSContractStatusMonitor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSContractStatusMonitor
     */
    @WebEndpoint(name = "WSContractStatusMonitor")
    public WSContractStatusMonitor getWSContractStatusMonitor(WebServiceFeature... features) {
        return super.getPort(new QName("http://common.status.contract.kernel.bgbilling.bitel.ru/", "WSContractStatusMonitor"), WSContractStatusMonitor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCONTRACTSTATUSMONITOR_EXCEPTION!= null) {
            throw WSCONTRACTSTATUSMONITOR_EXCEPTION;
        }
        return WSCONTRACTSTATUSMONITOR_WSDL_LOCATION;
    }

}
