
package ru.bgcrm.plugin.bgbilling.ws.contract.status;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import java.util.Date;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContractStatusMonitorService", targetNamespace = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
@Deprecated
public interface ContractStatusMonitorService {


    /**
     * 
     * @param onlyManual
     * @return
     *     returns java.util.List<ru.bgcrm.plugin.bgbilling.ws.contract.status.Status>
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatusList", targetNamespace = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.contract.status.GetStatusList")
    @ResponseWrapper(localName = "getStatusListResponse", targetNamespace = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.contract.status.GetStatusListResponse")
    @Action(input = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/getStatusListRequest", output = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/getStatusListResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/getStatusList/Fault/BGException")
    })
    public List<Status> getStatusList(
        @WebParam(name = "onlyManual", targetNamespace = "")
        boolean onlyManual)
        throws BGException_Exception
    ;

    /**
     * 
     * @throws BGException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createBalanceDump", targetNamespace = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.contract.status.CreateBalanceDump")
    @ResponseWrapper(localName = "createBalanceDumpResponse", targetNamespace = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.contract.status.CreateBalanceDumpResponse")
    @Action(input = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/createBalanceDumpRequest", output = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/createBalanceDumpResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/createBalanceDump/Fault/BGException")
    })
    public void createBalanceDump()
        throws BGException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg15
     * @param arg16
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @return
     *     returns ru.bgcrm.plugin.bgbilling.ws.contract.status.SearchResult
     * @throws BGException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "contractSearch", targetNamespace = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.contract.status.ContractSearch")
    @ResponseWrapper(localName = "contractSearchResponse", targetNamespace = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.contract.status.ContractSearchResponse")
    @Action(input = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/contractSearchRequest", output = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/contractSearchResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/contractSearch/Fault/BGException")
    })
    public SearchResult contractSearch(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<Integer> arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        List<Integer> arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        int arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        Page arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        int arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        BigDecimal arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        List<Integer> arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        float arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        int arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        int arg16)
        throws BGException_Exception
    ;

    /**
     * 
     * @param statusId
     * @param dateTo
     * @param comment
     * @param dateFrom
     * @param cid
     * @throws BGException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "changeContractStatus", targetNamespace = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.contract.status.ChangeContractStatus")
    @ResponseWrapper(localName = "changeContractStatusResponse", targetNamespace = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/", className = "ru.bgcrm.plugin.bgbilling.ws.contract.status.ChangeContractStatusResponse")
    @Action(input = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/changeContractStatusRequest", output = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/changeContractStatusResponse", fault = {
        @FaultAction(className = BGException_Exception.class, value = "http://service.common.status.contract.kernel.bgbilling.bitel.ru/ContractStatusMonitorService/changeContractStatus/Fault/BGException")
    })
    public void changeContractStatus(
        @WebParam(name = "cid", targetNamespace = "")
        List<Integer> cid,
        @WebParam(name = "statusId", targetNamespace = "")
        int statusId,
        @WebParam(name = "dateFrom", targetNamespace = "")
        Date dateFrom,
        @WebParam(name = "dateTo", targetNamespace = "")
        Date dateTo,
        @WebParam(name = "comment", targetNamespace = "")
        String comment)
        throws BGException_Exception
    ;

}
