= Примеры простой обработки событий
:toc:

== Kernel

[[create-process-and-link]]
=== Create a process and link int to the existing one
[source]
----
STATUS_IDS=1,4
PARAM_LIST_ID=49
PROCESS_TYPE_ID=8

onProcessEvent.{@inc:cnt}.events=statusChanged:{@STATUS_IDS}
onProcessEvent.{@cnt}.doExpression=<<END
    processId = event.getProcess().getId();

    dao = new("ru.bgcrm.dao.ParamValueDAO", conSet.getConnection());
    listValue = u.getFirst(dao.getParamList(processId,{@PARAM_LIST_ID}));

    log.debug("listValue: " + listValue);

    // if the list parameter value is 1
    if (listValue == 1) {
        // create a new process
        dao = new("ru.bgcrm.dao.process.ProcessDAO", conSet.getConnection());
        process = new("ru.bgcrm.model.process.Process");
        process.setTypeId({@PROCESS_TYPE_ID});
        process.setDescription("Created automatically");

        action = ru.bgcrm.struts.action.ProcessAction;
        action.processCreate(event.getForm(), conSet.getConnection(), process);

        log.debug("Created process: " + process.getId());

        // link it to the current one with relation type 'link'
        dao = new("ru.bgcrm.dao.process.ProcessLinkDAO", conSet.getConnection());
        link = new("org.bgerp.model.process.link.ProcessLinkProcess", processId, "processLink", process.getId());
        dao.addLink(link);
    }
END
----

[[add-process-customer-link]]
=== Add customer link to a created process
[source]
----
onProcessEvent.{@inc:cnt}.events=created
onProcessEvent.{@cnt}.doExpression=<<END
    customerId = 1;
    customerTitle = "Customer Title";
    dao=new("ru.bgcrm.dao.process.ProcessLinkDAO", conSet.getConnection());
    link=new("ru.bgcrm.model.CommonObjectLink", "process", process.getId(), "customer", customerId, customerTitle);
    dao.addLink(link);
END
----

[[check-change]]
=== Разрешение на правку процесса при различных условиях
В различных статусах различным группам, исполнителю либо администратору и запрет правки закрытого процесса.
[source]
----
onProcessEvent.{@inc:cnt}.checkExpression=process.getStatusId() !~ [9, 13, 36,39] or 8 =~ user.getGroupIds()
onProcessEvent.{@cnt}.checkErrorMessage=В этом статусе разрешена правка только сотрудникам КС
onProcessEvent.{@inc:cnt}.checkExpression=process.getStatusId() != 9 or user.getId()  =~ process.getExecutorIds() or 33 =~ user.getPermsetIds()
onProcessEvent.{@cnt}.checkErrorMessage=В этом статусе разрешена правка только исполнителем процесса либо администратором КС
onProcessEvent.{@inc:cnt}.checkExpression=process.getCloseTime() == null
onProcessEvent.{@cnt}.checkErrorMessage=Запрещена правка закрытого процесса
----

[[add-executor]]
=== Добавление пользователя в исполнители и смена статуса
Добавление текущего пользователя в исполнители и установка в статус с кодом 40, если процесс создан как привязанный к другому процессу.
[source]
----
onProcessEvent.{@inc:cnt}.events=createdAsLink
onProcessEvent.{@cnt}.doExpression=addExecutors({user.getId()});setStatus(40, "")
----

[[set-status]]
=== Установка статуса
Изменение статуса процесса на 3 при получении в него нового сообщения.
[source]
----
onProcessEvent.{@inc:cnt}.events=messageAdded
onProcessEvent.{@cnt}.ifExpression=process.getStatusId() != 3
onProcessEvent.{@cnt}.doExpression=setStatus(3, "")
----

[[set-param-text]]
=== Установка значения параметра типа text
[source]
----
onProcessEvent.{@inc:cnt}.doExpression=<<END
    dao = new("ru.bgcrm.dao.ParamValueDAO", conSet.getConnection());
    dao.updateParamText(process.getId(), 63, "тест");
END
----

[[set-param-list]]
=== Установка значения параметра типа list
[source]
----
onProcessEvent.{@inc:cnt}.doExpression=<<END
    dao = new("ru.bgcrm.dao.ParamValueDAO", conSet.getConnection());
    dao.updateParamList(process.getId(), 63, {1});
END
----

После изменения статуса если списковый параметр процесса 63 не содержит значений с кодами 1, 2 и 3 установка значения 1 в этот параметр.
[source]
----
onProcessEvent.{@inc:cnt}.events=statusChanged
onProcessEvent.{@cnt}.ifExpression=empty(cu.intersection(processParam.listValueIds(63), {1,2,3}))
onProcessEvent.{@cnt}.doExpression=<<END
    dao = new("ru.bgcrm.dao.ParamValueDAO", conSet.getConnection());
    dao.updateParamList(process.getId(), 63, {1});
END
----

[[remove-executors-and-groups]]
=== Удаление из процесса исполнителей и групп решения
C кодом 2 и группы с кодом 37.
[source]
----
onProcessEvent.{@inc:cnt}.doExpression=<<END
    deleteExecutors({2});
    deleteGroups({37});
END
----

[[set-date-on-create]]
=== При создании процесса установка параметра типа date
При создании процесса внесение в параметр типа "date" с кодом 51 значения текущей даты + два дня, не учитывая вторников.
[source]
----
onProcessEvent.{@inc:cnt}.events=created
onProcessEvent.{@cnt}.doExpression=<<END
    dao = new("ru.bgcrm.dao.ParamValueDAO", conSet.getConnection());
    cal = new("java.util.GregorianCalendar");
    addDays = 2;
    while (addDays > 0) {
        var dw = cal.get(cal.DAY_OF_WEEK);
        if (dw != cal.TUESDAY)
            addDays = addDays - 1;
        cal.add(cal.DAY_OF_YEAR, 1);
    }
    dao.updateParamDate(process.getId(), 51, cal.getTime());
END
----

[[change-status-linked-process]]
=== Смена статуса привязанного процесса
Поиск процесса, к которому привязан текущий процесс и если он найден - смена его статуса.
[source]
----
onProcessEvent.{@inc:cnt}.events=statusChanged
onProcessEvent.{@cnt}.doExpression=<<END
    pld = new("ru.bgcrm.dao.process.ProcessLinkDAO", conSet.getConnection());
    linked = u.getFirst(pld.getLinkedProcessList(process.getId(), null, false, {1}));
    if (linked != null) {
         change = new("ru.bgcrm.model.process.StatusChange");
        change.setDate(new("java.util.Date"));
        change.setProcessId(linked.getId());
        change.setUserId(event.getUser().getId());
        change.setStatusId(9);
        change.setComment("Автоматическая смена статуса");

        pa = ru.bgcrm.struts.action.ProcessAction;
        pa.processStatusUpdate(event.getForm(), conSet.getConnection(), linked, change);
    }
END
----

[[set-priority-on-status-change]]
=== Изменение приоритета процесса при смене статуса
При смене статуса на 10 или 12 установка приоритета 5.
----
onProcessEvent.{@inc:cnt}.events=statusChanged:10,12
onProcessEvent.{@cnt}.doExpression=setPriority(5);
----

[[check-event-class]]
=== Проверка класса события
[source]
----
if (event.getClass().getName() == "ru.bgcrm.event.process.ProcessMessageAddedEvent") {
    text += '<b>Сообщение</b>: ' + u.maskNull(event.getMessage().getText()) + ';';
}
----

[[add-description-on-status-change]]
=== Добавление текста в описание процесса при смене статуса
[source]
----
onProcessEvent.{@inc:cnt}.events=statusChanging
onProcessEvent.{@cnt}.doExpression=<<END
    dao = new("ru.bgcrm.dao.process.ProcessDAO", conSet.getConnection());

    change = event.getStatusChange();
    change = ctxUserMap[change.getUserId()].getTitle() + " => " + ctxProcessStatusMap[change.getStatusId()].getTitle() + " [" + change.getComment() + "]";

    process.setDescription(process.getDescription() + NEW_LINE + change);
    dao.updateProcess(process);
END
----

== Плагин <<../../plugin/bgbilling/index.adoc#, BGBilling>>
[[bgbilling-copy-params]]
=== Копирование параметров договора BGBilling
Копирование параметра адрес с кодом 8 из привязанного договора в параметр процесса с кодом 4.
Пример может быть легко расширен для переноса любых параметров.
[source]
----
COPY_BGBILLING_PARAMS=<<END
    paramDao = new("ru.bgcrm.dao.ParamValueDAO", conSet.getConnection());
    linkDao = new("ru.bgcrm.dao.process.ProcessLinkDAO", conSet.getConnection());
    contractLink = u.getFirst(linkDao.getObjectLinksWithType(process.getId(),"%contract%"));
    if (contractLink != null) {
         contractId =  contractLink.getLinkedObjectId();
         billingId = su.substringAfter(contractLink.getLinkedObjectType(), ":");
         contractParamDao = new("ru.bgcrm.plugin.bgbilling.proto.dao.ContractParamDAO", ctxUser, billingId);
         address = contractParamDao.getAddressParam(contractId, 8);
         if (address != null)
            paramDao.updateParamAddress(process.getId(), 4, 1, address.toParameterAddressValue(conSet.getConnection()));
         // копирование других параметров
    }
END

onProcessEvent.{@inc:cnt}.events=linkAdded;createdAsLink
onProcessEvent.{@cnt}.doExpression={@COPY_BGBILLING_PARAMS}
----

При привязке договора - копирование значений параметров с кодами 27 и 12 в описание процесса.
[source]
----
onProcessEvent.{@inc:cnt}.events=linkAdded
onProcessEvent.{@cnt}.commands=bgbilling:linkedContractParamToDescription:bg:27;bgbilling:linkedContractParamToDescription:bg:12
----

== Плагин <<../../plugin/msg/sms/index.adoc#, SMS>>
[[sms-send-sms]]
=== Отправка СМС
Отправка СМС сообщения по созданию процесса, в случае наличия в значениях спискового параметра с кодом 26 1, 2 или 3.
Используется операция пересечения множеств.
Номер для СМС получается из параметра с кодом 20 типа Phone.
[source]
----
onProcessEvent.{@inc:cnt}.events=createFinished
onProcessEvent.{@cnt}.ifExpression=cu.intersection(processParam.listValueIds(26), {1,2,3}).size() > 0
onProcessEvent.{@cnt}.doExpression=<<END
    phone=processParam.getParamPhoneNoFormat(20);
    if (phone) {
        sms.sendSms(phone, "Заявка №".concat( process.getId().toString() ).concat(" принята"));
    }
END
----

== Плагин <<../../plugin/mobile/index.adoc#, Mobile>>
[[mobile-send-push-notification]]
=== Отправка Push уведомления
Отправлка уведомление с параметрами процесса диспетчеру аварийной бригады.
Установлена проверка типа работ из параметра list id 26, передаются номер процесса, адрес, телефоны, тип работ, дата и время приема, комментарий.
[source]
----
onProcessEvent.{@inc:cnt}.events=createFinished
onProcessEvent.5.ifExpression=cu.intersection(processParam.listValueIds(26), {2,3,7}).size() > 0
onProcessEvent.5.doExpression=<<END
    body=process.getTypeTitle();
    text="№ " + process.getId().toString() + " Адрес: " + processParam.addressValues(1).toString() + " т. " + processParam.getValue(20) + " " + processParam.listValueTitles(26) + " Принята: " + process.getCreateTime() + " Комментарий: " + process.getDescription();
    mobile.sendMessageToUsers(body, text, {5});
END
----